#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# branch="$(git rev-parse --abbrev-ref HEAD)"

# if [ "$branch" = "main" ]; then
#   echo "Don't commit to main - it's bad luck ❌"
#   exit 1
# fi

echo '🏗️👷 Styling your project before committing...'

npx lint-staged || 
(
    echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
          Run yarn lint, add changes and try commit again.';
    false;
)

echo '🎉 Files linted, testing everything before committing....'


echo 'No errors found: committing this now.... ✨🚀🏄‍♂️🍻'